version: "3"
services:
  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm

  auto-login:
    image: smaranjawalkar/pes-captive-auto-login
    environment:
      - CAPTIVE_USERNAME=<username>
      - CAPTIVE_PASSWORD=<password>
      - SELENIUM_URL=http://selenium-chrome:4444
